# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cocoapods
      run: pod install
    - name: Build
      run: xcodebuild -workspace marvel-gallery.xcworkspace -scheme "marvel-gallery" -sdk "iphoneos"  build -allowProvisioningUpdates
    - name: Run tests
      run: xcodebuild -workspace marvel-gallery.xcworkspace -scheme "marvel-gallery" -sdk "iphoneos"  test -allowProvisioningUpdates
